const questions = [];
questions[0] = {q:" What is JavaScript?",A:"scripting language",B:"assembly language",C:"compiled language",D:"None of the mentioned",ans:"A"};
questions[1] = {q:" Which of the following is correct about JavaScript?",A:"Object-Based language",B:"assembly language",C:"Object-Oriented language",D:"High-level language",ans:"A"};
questions[2] = {q:"Define closures in JavaScript?",A:"A function with inner function scope",B:"A function with lexical environment",C:"A function with its inner function scope",D:"None of the mentioned",ans:"B"};
questions[3] = {q:"Arrays in JavaScript are defined by which of the following statements?",A:"It is an ordered list of values",B:"It is an ordered list of objects",C:"It is an ordered list of string",D:"It is an ordered list of functions",ans:"A"};
questions[4] = {q:"var js = (function(x) {return x*x;}(10));",A:"Exception will be thrown",B:"Memory leak",C:"Error",D:"Will work without error",ans:"D"};
questions[5] = {q:"Which of the following is not javascript data types?",A:"Null type",B:"Undefined type",C:"Number type",D:" All of the mentioned",ans:"D"};
questions[6] = {q:" Where is Client-side JavaScript code is embedded within HTML documents?",A:"Special javascript:code",B:"Special javascript:protocol",C:"Special javascript:encoding",D:"Special javascript:stack",ans:"D"};
questions[7] = {q:"Which of the following object is the main entry point to all client-side JavaScript features and APIs?",A:"Position",B:"Window",C:"Standard",D:"Location",ans:"B"};
questions[8] = {q:"Which of the following can be used to call a JavaScript Code Snippet?",A:"Function/windows Method",B:"Preprocessor",C:"Triggering Event",D:"RMI",ans:"A"};
questions[9] = {q:"What happens when a JavaScript program is developed on a Unix Machine?",A:"will work perfectly well on Windows",B:"JavaScript text on the browser",C:"will throw errors and exceptions",D:"restricted to a Unix Machine only",ans:"A"};
questions[10] = {q:"Which of the following scoping type does JavaScript use?",A:"Sequential",B:"Segmental",C:"Lexical",D:"Literal",ans:"C"};
questions[11] = {q:"What is the basic difference between JavaScript and Java?",A:"Functions are considered as fields",B:"No distinction between methods and fields",C:"Variables are specific",D:"There is no difference",ans:"B"};
questions[12] = {q:"Why JavaScript Engine is needed?",A:"Compiling & Interpreting the JavaScript",B:"Parsing the javascript",C:"Interpreting the JavaScript",D:"Compiling the JavaScript",ans:"C"};
questions[13] = {q:"Which of the following methods/operation does javascript use instead of == and !=?",A:"JavaScript uses equalto()",B:"uses equals() and notequals()",C:" uses bitwise checking",D:" uses === and !== instead",ans:"D"};
questions[14] = {q:"Why event handlers is needed in JS?",A:"To alter the behaviour of windows",B:"Adds innerHTML page to the code",C:"Change the server location",D:" handling of exceptions and occurrences",ans:"A"};
questions[15] = {q:"Which of the following is not a framework?",A:"JavaScript .NET",B:"JavaScript",C:"Cocoa JS",D:"jQuery",ans:"B"};
questions[16] = {q:" Which of the following is the property that is triggered in response to JS errors?",A:"onclick",B:"onerror",C:"onmessage",D:"onexception",ans:"B"};
questions[17] = {q:"Which of the following is not an error in JavaScript?",A:"Missing of Bracket",B:"Division by zero",C:"Syntax error",D:"Missing of semicolons",ans:"B"};
questions[18] = {q:"The behaviour of the instances present of a class inside a method is defined by ",A:"Method",B:"Classes",C:"Interfaces",D:"Classes and Interfaces",ans:"B"};
questions[19] = {q:"The keyword used to refer to an object through which they were invoked is",A:"from",B:"to",C:"this",D:"object",ans:"C"};
questions[20] = {q:"The basic difference between JavaScript and Java is",A:"There is no difference",B:"Functions are considered as fields",C:"Variables are specific",D:"no hard distinction between methods and fields",ans:"D"};
questions[21] = {q:"The meaning for Augmenting classes is that...",A:"objects inherit even in a dynamic state",B:"objects inherit only in a dynamic state",C:"objects inherit in the static state",D:"object doesn’t inherit in the static state",ans:"A"};
questions[22] = {q:"The property of JSON() method is...",A:"it can be invoked manually as object.JSON()",B:"it will be automatically invoked by the compiler",C:"invoked automatically by the JSON.stringify() ",D:"it cannot be invoked in any form",ans:"C"};